# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' group-name ''
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' original true
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000000
bindkey -e
# End of lines configured by zsh-newuser-install

# Setup functionalities
autoload -Uz colors
colors

# Core variable declarations
export PATH=$PATH:/usr/local/sbin
export PROMPT="%{${fg[cyan]}%}%~ %{${fg[red]}%}❯%{${fg[yellow]}%}❯%{${fg[green]}%}❯%{${reset_color}%} "

# Aliases
alias ls="ls --color"
alias gst="git status -s -b"
